import fs from 'node:fs';
import path from 'node:path';
import { EnvAstEntry, EnvFileAst, EnvVariable } from '../parser/types.js';
import { parseEnv, serializeEnv } from '../parser/env-parser.js';
import { generateSafePlaceholder } from './masker.js';

export interface SyncOptions {
  cwd?: string;
  envPath?: string;
  examplePath?: string;
  prune?: boolean;
  addTypeAnnotations?: boolean;
  codeKeys?: Set<string>;
}

export interface SyncResult {
  addedKeys: string[];
  prunedKeys: string[];
  updatedContent: string;
  examplePath: string;
  isNewFile: boolean;
}

/**
 * Synchronizes and updates .env.example with variables from .env and source code references.
 */
export function syncEnvExample(options: SyncOptions = {}): SyncResult {
  const cwd = options.cwd ? path.resolve(options.cwd) : process.cwd();
  const envPath = path.resolve(cwd, options.envPath || '.env');
  const examplePath = path.resolve(cwd, options.examplePath || '.env.example');

  let envAst: EnvFileAst | null = null;
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envAst = parseEnv(envContent, { filePath: envPath });
  }

  const isNewFile = !fs.existsSync(examplePath);
  let exampleAst: EnvFileAst = {
    filePath: examplePath,
    entries: [],
    variables: new Map(),
    rawContent: ''
  };

  if (!isNewFile) {
    const exampleContent = fs.readFileSync(examplePath, 'utf8');
    exampleAst = parseEnv(exampleContent, { filePath: examplePath });
  }

  const envVars = envAst?.variables || new Map<string, EnvVariable>();
  const exampleVars = exampleAst.variables;
  const codeKeys = options.codeKeys || new Set<string>();

  // Gather all known variable keys (from .env and code references)
  const allKnownKeys = new Set<string>([...envVars.keys(), ...codeKeys]);

  const addedKeys: string[] = [];
  const prunedKeys: string[] = [];

  // 1. Identify missing keys to add to .env.example
  const missingKeys: string[] = [];
  for (const key of allKnownKeys) {
    if (!exampleVars.has(key)) {
      missingKeys.push(key);
      addedKeys.push(key);
    }
  }

  // 2. If prune option is set, remove keys from .env.example that are not in .env and not in code
  let updatedEntries: EnvAstEntry[] = [...exampleAst.entries];

  if (options.prune) {
    const retainedEntries: EnvAstEntry[] = [];
    for (const entry of updatedEntries) {
      if (entry.type === 'variable') {
        if (!allKnownKeys.has(entry.key)) {
          prunedKeys.push(entry.key);
          continue; // skip / prune
        }
      }
      retainedEntries.push(entry);
    }
    updatedEntries = retainedEntries;
  }

  // 3. Append missing keys with smart placeholders and annotations
  if (missingKeys.length > 0) {
    // Add separator if not empty and doesn't end with newline
    if (updatedEntries.length > 0) {
      const lastEntry = updatedEntries[updatedEntries.length - 1];
      if (lastEntry.type !== 'empty') {
        updatedEntries.push({ type: 'empty', line: updatedEntries.length + 1 });
      }
      updatedEntries.push({
        type: 'comment',
        comment: '# Auto-generated by envguard',
        line: updatedEntries.length + 1
      });
    }

    for (const key of missingKeys) {
      const currentEnvVal = envVars.get(key)?.value;
      const { value: placeholder, inferredType } = generateSafePlaceholder(key, currentEnvVal);

      let inlineComment: string | undefined;
      if (options.addTypeAnnotations !== false) {
        inlineComment = `# @type ${inferredType}`;
      }

      const newVar: EnvVariable = {
        type: 'variable',
        key,
        value: placeholder,
        raw: `${key}=${placeholder}`,
        line: updatedEntries.length + 1,
        inlineComment,
        annotations: {
          type: inferredType,
          required: true
        }
      };

      updatedEntries.push(newVar);
    }
  }

  const updatedAst: EnvFileAst = {
    filePath: examplePath,
    entries: updatedEntries,
    variables: new Map(),
    rawContent: ''
  };

  const updatedContent = serializeEnv(updatedAst);
  fs.writeFileSync(examplePath, updatedContent, 'utf8');

  return {
    addedKeys,
    prunedKeys,
    updatedContent,
    examplePath,
    isNewFile
  };
}
