import fs from 'node:fs';
import path from 'node:path';
import { EnvFileAst, InferredType } from '../parser/types.js';
import { inferType } from '../validator/type-inference.js';

export interface GenerateTypesOptions {
  cwd?: string;
  outputPath?: string;
  envAst?: EnvFileAst | null;
  exampleAst?: EnvFileAst | null;
  codeKeys?: Set<string>;
}

export interface GenerateTypesResult {
  outputPath: string;
  content: string;
  variablesCount: number;
}

/**
 * Maps InferredType to TypeScript type syntax.
 */
function mapToTsType(inferred: InferredType | string, enumValues?: string[]): string {
  if (inferred === 'enum' && enumValues && enumValues.length > 0) {
    return enumValues.map((val) => `'${val}'`).join(' | ');
  }

  switch (inferred) {
    case 'port':
    case 'number':
    case 'integer':
    case 'float':
      return '`${number}` | string'; // In Node.js process.env values are strings at runtime
    case 'boolean':
    case 'bool':
      return "'true' | 'false' | '1' | '0'";
    default:
      return 'string';
  }
}

/**
 * Generates TypeScript type declarations (env.d.ts) for process.env and import.meta.env.
 */
export function generateTypeDeclarations(options: GenerateTypesOptions = {}): GenerateTypesResult {
  const cwd = options.cwd ? path.resolve(options.cwd) : process.cwd();
  const outputPath = path.resolve(cwd, options.outputPath || 'env.d.ts');

  // Collect all known variables and their inferred types
  const schemaMap = new Map<string, { type: string; description?: string; required: boolean }>();

  // Extract from example AST
  if (options.exampleAst) {
    for (const [key, envVar] of options.exampleAst.variables.entries()) {
      const typeStr = envVar.annotations.type || inferType(envVar.value, key);
      schemaMap.set(key, {
        type: mapToTsType(typeStr, envVar.annotations.enumValues),
        description: envVar.annotations.description,
        required: envVar.annotations.required !== false
      });
    }
  }

  // Extract from actual .env AST
  if (options.envAst) {
    for (const [key, envVar] of options.envAst.variables.entries()) {
      if (!schemaMap.has(key)) {
        const typeStr = inferType(envVar.value, key);
        schemaMap.set(key, {
          type: mapToTsType(typeStr),
          required: true
        });
      }
    }
  }

  // Extract from code references
  if (options.codeKeys) {
    for (const codeKey of options.codeKeys) {
      if (!schemaMap.has(codeKey)) {
        schemaMap.set(codeKey, {
          type: 'string',
          required: true
        });
      }
    }
  }

  const sortedKeys = Array.from(schemaMap.keys()).sort();
  const entries: string[] = [];
  for (const key of sortedKeys) {
    const meta = schemaMap.get(key)!;
    const doc = meta.description ? `    /** ${meta.description} */\n` : '';
    const optional = meta.required ? '' : '?';
    entries.push(`${doc}    ${key}${optional}: ${meta.type};`);
  }

  const content = `// Generated by envguard. Do not edit manually.
// Run "npx envguard gen-types" to regenerate.

declare global {
  namespace NodeJS {
    interface ProcessEnv {
${entries.join('\n')}
    }
  }

  interface ImportMetaEnv {
${entries.join('\n')}
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

export {};
`;

  // Write out the file
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, 'utf8');

  return {
    outputPath,
    content,
    variablesCount: schemaMap.size
  };
}
